---
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: photoprism
  namespace: photoprism
spec:
  hosts:
    - photos.paas.lsedlar.cz
  scaleTargetRef:
    name: photoprism-photoprism
    kind: StatefulSet
    apiVersion: apps/v1
    service: photoprism-photoprism
    port: 2342
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 300
