---
# TODO: Replace PLACEHOLDER with an actual sealed value.
# 1. Create a Forgejo bot account with a PAT that has these scopes:
#      repo: Read and Write
#      user: Read
#      issue: Read and Write
#      organization: Read
# 2. Seal the token:
#      echo -n 'your-token' | kubeseal --raw --namespace renovate --name renovate-secret --from-file=/dev/stdin
# 3. Replace PLACEHOLDER below with the output.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-secret
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgA1I6m+asyG1ML+fVluWZW2BJqVNbD/N9QMx6BfGnqmJ0qG6FxAp+m+E3M4ROjf5Vd26v9du25zF0XEd1khmbj/ySUv4ixRvf7eOr0pczm8RX1hk5z2QDS1urKqOHKRTJd6H4BSAMHH5Gn3hw5arKofdeNKHeLVPD7OSQLDxjPPRscST7iYWMNo/Jh2o1dQtJFc8V8A+m3m/tXaetvRV27r9vqELCHPadGsTCjlrPorxHPR7KB1y5YkMO5pMZ/G80efKmY0dInqcWDA5/wcyEPP95EoIXV/T8im7q+GHOP6XkvhA/wb1DJhltAlU817hTcQFrVr+o+TZRETAPn73r8YQtaF2hT2uD2i6tLc+AS43crWquoJaoCfXADwi6Q51tZfb0w9IZKoDiAEfv6qM7g8Qi5LY1EkPUMbSdqo9a2nZBxg1sWkd73Wy9/WpKCA9Ap4kAUxq44qQNzyODX/jS1WoGJtS1nFrxnMMgtleZ7Oevu7SyeJzl7JA3evHUIcyfWTpdQmW0ORwfIC/yj8k00ss3AEJK357DOMymAjm/xRYkeU0LMEggbUVqShT8zmzlHGHt/BHMebjLL43dbO5DC+ffySMVvcvjPY7j+br1nSzc2SjLMDuxKnY9dS38/P9awKoBsq5RkbVcUzckah6bMmSMzVyA5WGRn45HW5b7mitRT09u/J49az8SNSBc2TJlnl+SDgZjwbGEiHTpsv4sAJM+6SZeVK6Y6WIru4DjYMHHc2kXVB9rqg
  template:
    metadata:
      name: renovate-secret
      namespace: renovate
    type: Opaque
