---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather-downsample
  namespace: weather-station
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 14
  failedJobsHistoryLimit: 14
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1000
          containers:
          - name: downsample
            image: docker.io/lsedlar/weather-station-receiver:1.0.12@sha256:0aa2b1c260295086c8fd3254a32aec8899b3e58d5c838a461619596397be370d
            imagePullPolicy: IfNotPresent
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              readOnlyRootFilesystem: true
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 256Mi
            command:
            - python
            - /app/downsampler.py
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: databaseUrl
                  name: weather-station-postgres-weather-station-db-user
          restartPolicy: Never
