---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather-downsample
  namespace: weather-station
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1000
          containers:
          - name: downsample
            image: docker.io/lsedlar/weather-station-receiver:2.0.0@sha256:c6302619ce0f51d55dd7c314b9ad3e093a955f9705767c83d32ddf3262690564
            imagePullPolicy: IfNotPresent
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              readOnlyRootFilesystem: true
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 256Mi
            command:
            - /app/.venv/bin/receiver-downsampler
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: databaseUrl
                  name: weather-station-postgres-weather-station-db-user
          restartPolicy: Never
