---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weather-station-data
  namespace: weather-station
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
