---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: postgresql
spec:
  encryptedData:
    postgres-password: AgA+iB3P32XeV3/rLMlED8uG1nu/PLzhcu7iuvMX1g3qm3C4FvlFBjmQm6KnpJZbxLK5IfvhDKEwhjguNsDvsw1CN4NC+zxAtTGmljgdFuezOzdUvnf53bKrF9iUR4I8GM2jkcuCurUMajFSDtvIIUSrR1plDz0BZ0wM/u29e8kGeJERm50dNLl+ftYqkGZVVaybbKw4Bt4KFJHZ8L3lhg1keeBGMq2Capi02jv7EttwRHPssNuO6GIm4lx1FzVxMHwgq3+v2OdjZcmYSzj2xBeR8kXCbkIt83tbBk+eHHF6OzxRi/JSKUcKXVHLOLnzoC3NBjrDTW/O1BiRG5vfQTBa7XeBN//7FVY2zK+8ZAOb0YJ3WG5JBwJbiPWmZLAqiRSyf93g0D+ac9NN0ILs70qDTgLiXiznt2S//U0e+cVrTzd1WdN3DArwU00hACWDO3t1NQ3yNxuEtEjvLpMrjuWADL6+LpfWEvwNUPO18xdqnSnLMp/Hga6K8ejo54c+dS1UWrdkD0ZXBUnuCzVJVx6d4XrvqtxhsX5wZqyelELYYq+LfSazamBPtXHJjVcAyraZ3pViHWAnxBKGgEJqJWKkdLDjDxej1C09CvP8gRTl9I7wcefrlbmNZ4mXnb6YE87n+/vvJsMTf1DT43AAO1r+dj33Kj0tCaDSROfttqNMCjbryxo8nvQV+QDPx8wTrnosHTXloGRQo5ZcchkvTYzKvhaV7zKAlXL6toqF6XvFj5ZfYDTGw1ck1V10JXBDpIfMpDKAXIcY2m1FGBjmlikpUIsIvAHefFFcdTnO
  template:
    metadata:
      name: postgresql-secret
      namespace: postgresql
