---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rauthy-config
  namespace: rauthy
data:
  config.toml: |
    [server]
    pub_url = "sso.paas.lsedlar.cz"
    listen_address = "0.0.0.0"
    port_http = 8080
    scheme = "http"
    proxy_mode = true
    trusted_proxies = ["172.30.0.0/24"]

    [cluster]
    node_id = 1
    secret_raft = "placeholder_not_used_with_postgres"
    secret_api = "placeholder_not_used_with_postgres"

    [database]
    hiqlite = false

    [email]
    smtp_url = "smtp.gmail.com"

    [webauthn]
    rp_id = "sso.paas.lsedlar.cz"
    rp_origin = "https://sso.paas.lsedlar.cz:443"
    rp_name = "Rauthy IAM"
