---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rauthy
  namespace: rauthy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rauthy
  template:
    metadata:
      labels:
        app: rauthy
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: rauthy
          image: ghcr.io/sebadob/rauthy:0.35.1@sha256:a8637f70bae57fd9a334dcdc92765e1fb56f8a4f2e043926695e7b3530ffa729
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 256Mi
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  key: PG_HOST
                  name: rauthy-postgres-rauthy-db-user
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  key: PG_PORT
                  name: rauthy-postgres-rauthy-db-user
            - name: PG_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: PG_DB_NAME
                  name: rauthy-postgres-rauthy-db-user
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  key: PG_USER
                  name: rauthy-postgres-rauthy-db-user
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PG_PASSWORD
                  name: rauthy-postgres-rauthy-db-user
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  key: SMTP_USERNAME
                  name: rauthy-secrets
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SMTP_PASSWORD
                  name: rauthy-secrets
            - name: ENC_KEYS
              valueFrom:
                secretKeyRef:
                  key: ENC_KEYS
                  name: rauthy-secrets
            - name: ENC_KEY_ACTIVE
              valueFrom:
                secretKeyRef:
                  key: ENC_KEY_ACTIVE
                  name: rauthy-secrets
          livenessProbe:
            httpGet:
              path: /auth/v1/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /ready
              port: 8200
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 2
          volumeMounts:
            - name: rauthy-config
              mountPath: /app/config.toml
              readOnly: true
              subPath: config.toml
      volumes:
        - name: rauthy-config
          configMap:
            name: rauthy-config
