---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rauthy-secrets
  namespace: rauthy
spec:
  encryptedData:
    ENC_KEY_ACTIVE: AgAxd0rurEyOw9W92/+asPWDk8sWt9zq4ImfitTnFD14VVXEky9FUCJSi+bZClQKTEF0LrXGkwKX4dwrn98Iai+TTlKi3dE1IRmqtdM8qRjNxoyFS+ly+8v2wOnCC72TsE9SpSTfThUj+1jZXzJ+ucfE/N/SyB+mK8fS96g6HdQwsGUcm8jr+PLnpsAoYqx65gUCEXxgioquIuxiOl9Y+HK/8Xzpr01W1UwRxX9x+tfUi4tXJ5r+03C/689qki1lpTfP2cBEmF+SejxaPHtYTf7jRg46nSI8OCZbNpD0t4glA1nv0B72iqqcb8oKbhMIlyEvMeBVEEzmOcND9enotK9IcqerPaIPTvcVRdP6ZMLzFJc6eS3Z0E8P1KcQe1nP98JElna43vaxmC0uTNDMqiyiesTEDXNvVELt1lyxxis8soLEzGWxqJdiKb6/CxH57du8N6ShNWUPquEyqihSPUnjGARaJSYkgWSR6cde4afiYL8LnIe3Hthb3im4UrZSCoaq3TPTaf2gLUzJnN6Z7KRzILQXv0gumDGL68rn7JPzZrSVmGtwPh4WVZpMdnogVsrLTaCeE4XFryQUjypTnxVCUC3TXW+LFpXshJ2b5UW/o4Tp5VjDIuQ/FxCZjulnQgUkWfHpxBedJ0BDvCTdyKSQdU8TXr3P5vmFMY1L9X8eNFREogewxmOGBNWPZQ7xZdxcdAvM
    ENC_KEYS: AgATznkhGsTP6uk97ROQKhLD7SWknMddQcEr31Ku3+C+E/sQ9uhdP3WedwFbSIGrOhwWuLz3EMVEHsjj+eul/CO5nT5067YlZLUu5FQUUBwEHtTt+LO2W0/hvS0K61+lVMtajKdVxGeUsdyyo9ywq/+K4SFjCkXIyQlg//8oTltv1GGOL2C4SrNahcQFPu+Wh0klOcK6mCdh124vssN1evjEsyR36xV1Yijf8O42/ta1F2xoyuvJbHUsD33gowErtx6WOv+F11R3WSWs7S7ZPgbSgziQozWRIWdXQTlug0pjePH5ahC9ozQXW/M/HOta+KIXaAAkWj1M4l9aUT4A+aJpdTgZdmcVW1zWd7IlTxWBQypCCYmmZzPk3FH22oiMtcWV/MyUfjGJPpqMysD2yVEwmeuhYlthQaZ0ECmdcUtcPJnPK3PSfNml3RAYX+4AZvz2qhqC3UN9Knik+do1TPB8hYhNrOLp6LQtvEmHP8Et/KXFtekflF9I65TLqUQhpX2iJ/LUbKdL0HZ7Yv5I1gqg5d0vES1skufj+K4u0A9cruf9QkyYdy+qwldV4b9INM/g+5/S6IyWYqjVaQaG1vtmZC+I1T3e12trosN+xgPvBayL9vfcCS9QQe4Xjs808rt7CI1uUn2JDkDITLiG8IrKRX+9lDGIGKSBB63EITLXfF/21JN2Gtv5ipKc2AjH0QyJsuY+/jSMWuS6O6stYX2ItuusOV8BGomI0rXuRdEPdxLQSMmwPQ6YX8RC9ZdIJsI3
  template:
    metadata:
      name: rauthy-secrets
      namespace: rauthy
