---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: forgejo-runner
  namespace: forgejo
  labels:
    app: forgejo-runner
spec:
  jobTargetRef:
    activeDeadlineSeconds: 3600
    backoffLimit: 0
    template:
      metadata:
        labels:
          app: forgejo-runner
      spec:
        restartPolicy: Never
        shareProcessNamespace: true
        containers:
          - name: runner
            image: code.forgejo.org/forgejo/runner:12.7.1
            resources:
              requests:
                cpu: 20m
                memory: 128Mi
              limits:
                memory: 512Mi
            command:
              - sh
              - -c
              - |
                while ! nc -z localhost 2376 ; do
                  echo 'waiting for docker daemon...'
                  sleep 6
                done
                cp /secret/RUNNER_CONFIG /data/.runner
                exec forgejo-runner -c /config/config.yaml one-job
            env:
              - name: DOCKER_HOST
                value: tcp://localhost:2376
              - name: DOCKER_CERT_PATH
                value: /certs/client
              - name: DOCKER_TLS_VERIFY
                value: "1"
            volumeMounts:
              - name: runner-data
                mountPath: /data
              - name: runner-config
                mountPath: /config
                readOnly: true
              - name: runner-secret
                mountPath: /secret
                readOnly: true
              - name: docker-certs
                mountPath: /certs
          - name: dind
            image: docker:29-dind@sha256:4d90f1f6c400315c2dba96d3ec93c01e64198395cbba04f79d12adce4f737029
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 20m
                memory: 128Mi
              limits:
                memory: 1Gi
            command:
              - sh
              - -c
              - |
                dockerd-entrypoint.sh 2>&1 &

                # Give forgejo a moment to start
                sleep 30

                while pgrep forgejo-runner 2>/dev/null >/dev/null; do
                    sleep 10
                    echo "watching main job execution"
                done

                sleep 10

                echo "main container exited, stopping dind"
                exit 0
            env:
              - name: DOCKER_TLS_CERTDIR
                value: /certs
            volumeMounts:
              - name: docker-storage
                mountPath: /var/lib/docker
              - name: docker-certs
                mountPath: /certs
        volumes:
          - name: runner-data
            persistentVolumeClaim:
              claimName: forgejo-runner-cache
          - name: runner-config
            configMap:
              name: forgejo-runner-config
          - name: runner-secret
            secret:
              secretName: forgejo-runner-secret
          - name: docker-storage
            persistentVolumeClaim:
              claimName: forgejo-dind-storage
          - name: docker-certs
            emptyDir: {}
  pollingInterval: 30
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  minReplicaCount: 0
  maxReplicaCount: 1
  triggers:
    - type: forgejo-runner
      metadata:
        name: "k8s-runner-1"
        address: "http://forgejo-http.forgejo.svc.cluster.local"
        global: "true"
        labels: "docker"
      authenticationRef:
        name: forgejo-runner-keda-creds
