---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-keda-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgB531e3KYbwveG1JIAhdjUJHwnNj4CRuGJUzlj0Ew/MBj8J6S7j2JGKOselQgRv6IDEkfCEaQivDMNBOWFVKiwTybueszqSdmpxRvE54/6HTblYhYLcX2o/B04v6Oa2JsQu2gCUS0XqcEnF9A1OVHN0kpMZzdgVPhV57b2etLKfLKC11P/kL4m2F88b/z8xzXqjqnsUA7faaUwBTnHfqs9g46jftrG0T8bXHEhvXkoVfCl6fqP/y/NikllaCefSDSk71BA+DmVD4VmONSPWNhYzD3NIhUxkrP1rivTEGmy7M996GyH8Nt56J0EvJtKTBjBz+ub8wez3VxG6BDArPm/wlHOFCtz1G+jA5wvS/Xf1SDQ40f0FN5fVeTPhHNROPz1LNI2a4AtClXClmbIapJKUZnngyIWl9lUYGagRSKn7oSE0kETl4FaV03Ai+34QxSgWKtZvULrgGnO7levkt1fKkrlD21oUGG/i3NFEtoJkq6Cb+xvq1bsSdcxgJXWxnvTMDspcGZHoi3FsrNFd0Vbn5o0Ldmwdf6sWtzPDm6PnnetBea7bAezHMhjfCjFf3EtR5da7ACdmAoEzHrWYT/O5b5fSVsp72JNesc81yQwb6l3vfOtA6CGSMw5XI4IRSUphDSfGsqu4Vz/Dj7K/MGHK/G8TjTrzcltdNo97cT4gjGIO5J1vrLx0q1i3gE8hJOhPwihQZtTQnAmT1mHRR36a2EfjY6GwYjgH4jgtd49EDpAiwL0ov3c3MQ==
  template:
    metadata:
      name: forgejo-keda-secret
      namespace: forgejo
    type: Opaque
