---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    RUNNER_TOKEN: AgChmJ6Uoq75OuJYj6CH7Odm5cfFm2UXv8oAnjYddipRmiTJoPmfnm6arwFvKEFt2aEc1Pn4RIaLUX3VjkPBHdS7qk7gazcFKcgOI6bV1x6XBNn/vcSSNJe2d1ZdvgHYlC7WM5kFU0ZXiPODrrTtoK8TnzDRAiog7JV3P6ZvPqVTRF33d2UFE6I0JDf9hRfOsiJLsj5YvRUWUA+KYPNjS1IRZMBLiNYYpSOfB4DGF8qJdM8bd7cYMXTeEKVM6DAQRB8TmRzSSS1nU3JMxb320kW4RwLH7+ENh6kaJKI+0mlxWB8efSu9f+vzUXHTSbuf/M/3xfDC64ZEz5lkHHG8sMvnzwDPqpmZwK7CrCQJMadENbamLPY3PV2ZFgplcpVv7MqswlvA+hZaJREihYxGOG11DJtl+QRlPm3cRKabIbRpNpssLJXdntwJ866MqP4PsD5K4RdMNbjWOW51fsFklmuOK8LQ10t9lSYMXJntKEsfkYL++WUfT23u4pBjr+3iUx+5EdXFVnHB454HQfjtkvCSdNeGpRxVNbXZQGR5JNHhtOTfngMMivfgvLzS7BPI1aMKdKmdezOZ76PnSWjM45uqJjAEuhOq3HzMLpBpeyX+GN7IOJjkxxnPuT0jlfo6OXkZJSq+2uLcbp/qXJjFyKh0zsjlKBfuZTxNmRMhxXRcaKtjkzwdqnf+rJ0+HGjFp2I33xDh3Y7h4IFfJiGrv6Cty36tWPKs4DBSjvxDasGx48l493d2dK0p24B3
  template:
    metadata:
      name: forgejo-runner-secret
      namespace: forgejo
    type: Opaque
