---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-keda-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgCmtZPVvc0OeQ0bpM5r3XujCC1GCyhWVQHRh8x40DFdioGjqlqNoXUtUMqYtFhjvbzV0BSLaK9hugmXBf0NjdkpTDWSZrycE0JoNgUoo0O+rG2XlI+n51yDCzSyrC+87T+wzXoDXctdUqnjfI0bZw95iUwP4TPsh27BBiZI7uVLZ3axi4y80Skxn8dw3YydtLbYJDmeTm20AV3tXUX08Cep/t1b7FcsFXQNUsazHc0bkkip9c+9BnR3Uf+QrwUNrTSYmjYUQTostRGVTV5pqwEpwFBNBViuP0LN743Czb4qniCdlMKHsalWgO26AcyK/IFUMSWp2OOCXY717fcF5S7oJhxgC02y+FMu72lKb2EVbfV9qH/bz9W2USr7FIBzflGLv6mUN6TNvBSDLJWV5Dmy6pZIZPS5PMOfJAER9t1pwgfYBraPsP/vPpgF1E+GZXDdDukrIQno6fNJ41UO4beB4WqiL/pGMB38S90JWJPYRCuKfOfHfZbfaFBe6es4RvZ0ecBFrhSj7qlQBdREtOxm2InCSwQTN2J+A2I2At92VkE/RYMQuIhgik18FnJhx/q/ke0CjtW8to/t94+sjZnE3JvtK9vFa43tgDhxYdD3GZgtR2JJhN7MLCPkmYjyv2uhw994dQVMrysuiq3FUbJ8cw7ZCgvjUhalxX8sKXDHrNeWsJ2sj4o05QilTppTJp4oY7hkz/9zJsBtg9hopZM65glbbg9rmcqGRtIPtgEZKHAcC7VWcZKIxA==
  template:
    metadata:
      name: forgejo-keda-secret
      namespace: forgejo
    type: Opaque
