---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: forgejo-runner-keda-creds
  namespace: forgejo
spec:
  secretTargetRef:
    - parameter: token
      name: forgejo-keda-secret
      key: token
