---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    email-password: AgAUmE+RedkNhCtpFcIAAv9U8ryNeH8fUIaVgMwJlg3Wa0D/8S8KqPILL75xWEszbiJgtTbQ9QI9J03gAqkSpGb+PXCvKI+NSuajmlKyFSDRzeruWq0IwoDYxd/R4C6bGuMVgCFj67IJQ5F4japQ4851LJSFhzylJ4fx4i0dSdZhX3G3A5l1v9i6n9TvqSFwKRRIl0u3bNPrK9qD+HPjs/ZtYrpaCbImvh/vU810A0Nt7KkTmwI6K47q9jnBs5S9Gm6sx/mgB5vkhKFn+CmKyK/2dsm2UCE6W4qW8IZ5iVY66LlkaUoGMLy773yptNhv2J661mm5ENbnOx1M3ymolTdgctQOTwIMmYaMWetbxq7qdwN0GRpoSYzAjeVseWYouD8PKFYVrxvmBej5F8q3lirLDbipn+VHbHn//NnazxOMOd9Lvz05VALdDtdLYF1SbDZ4YD8YVt5vqMMhuEgn5TUKVzy79yJB7VoFWALBCfBNTcIoY9A430UAnjoOCjXv9fCQZjk274NXajpcUsYuB1WMctM4vd+K0ei+Hhj8OH+A1gIn3gCS2cMpCwRc6nVe4pVKcpYy/1ne7teynceUuGMeSO97QVEDMB+bLat4OtN3tuxkKCFlKRa7BD2kp/5aihbVXQem+j5wX/WQ7WZZ168+mix+x3IXJIcP/bD4avK3dbvy5ATmBtzIhBpXHmSivx1DMrWUl4Nwu1SloGjEbycd
    email-username: AgBmVo8y6koE6R8t34OgayFTZoJGzYSLrdPvnOFleUWtZ2OZhESlKtRkdAnANuexOLalsed4AO9rlgZscxHaP8tsCuNBSKeibwc+dNtuw5RXFV1BuDOkiiptgso9t1wo0pM2WnRZ2UpaqYyfAHc7w/LURjd7wQAxqc6kx5VSRJHU11PAXmCKIaB9k+la9WmadRe9M1W5ZicKFJmPHXMEq9dRkr8FbwxWUxM0sJ9xZ5Y7sPIZi88FX7q8KDO4P0G7ImX9VxMxlXXLIvEPMFbbMw9PHgZ4X7z6suNrxtjAeHTzCqgjevgkYNxJAEzI1OnfIs/dYEiEmVQDzmIFLTyU5l2eW/ltxB4irtsKz2coCbnOZRujf/J9p70zEeJEgR4TLRPqinTdSyQC06AeRFHHNFTt2bh5rDOIC7VCbaWb1cj25i4tinAKWApvmb8Se424XwSRF4GmRVGOa68CibSGwz3gUs+VJ5bE9FXKJ9xAnFNLijXvPp+YMsLYgOj/Jy4/Z3tYdHXDJJG/b5IDK/e0m8kYp/N3FSLSDjcVsH55adpkxQGZeSv0Y/6QK1DZ12AKkBONJrNVdnbonLggyAFOJfkNkN4sNWB59iL8lk3gz0/TvDtNTssVB6yH8L2i3yUbi3DfwuHGAIYeLy25dXL6S3VAy4YkSimZpIBwMvwjuc83U25DHrfD8fu/w3SStx9870n2HEeWB+EN32rI7bq8OrhlK+IdOQ8zuz0=
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
