apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pi-root
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/lubomir/pibox-gitops.git
    targetRevision: main
    path: clusters/pibox/apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
