---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: global-fail2ban
  namespace: traefik
spec:
  plugin:
    fail2ban:
      rules:
        bantime: "24h"
        findtime: "5m"
        maxretry: 5
        statuscode: "302,401,403,404,429"
        enabled: true
