---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  custom.server: |
    template IN A paas.lsedlar.cz {
        match ".*\.paas\.lsedlar\.cz\.$"
        answer "{{ .Name }} 60 IN A 192.168.0.120"
        fallthrough
    }
