---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  custom.server: |
    paas.lsedlar.cz:53 {
        hosts {
            192.168.0.120 git.paas.lsedlar.cz grafana.paas.lsedlar.cz sso.paas.lsedlar.cz photos.paas.lsedlar.cz ww.paas.lsedlar.cz
            fallthrough
        }
    }
