---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  local-hairpin.override: |
    rewrite name exact git.paas.lsedlar.cz my-traefik.traefik.svc.cluster.local
    rewrite name exact grafana.paas.lsedlar.cz my-traefik.traefik.svc.cluster.local
    rewrite name exact sso.paas.lsedlar.cz my-traefik.traefik.svc.cluster.local
    rewrite name exact photos.paas.lsedlar.cz my-traefik.traefik.svc.cluster.local
    rewrite name exact ww.paas.lsedlar.cz my-traefik.traefik.svc.cluster.local
