---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-traefik
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 39.0.2
    helm:
      values: |
        providers:
          kubernetesIngress:
            allowExternalNameServices: true
            publishedService:
              enabled: true
        ports:
          web:
            http:
              redirections:
                entryPoint:
                  to: websecure
                  scheme: https

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
